"""
Python script to run the end-to-end Antescofo/PureData OSC demo.

PRE-REQUISITES:
1. PureData is running.
2. The 'pd_synth_patch.pd' file is open in Pd.
3. Antescofo external is loaded and configured in the Pd patch.
4. The 'simple_demo_score.asco.txt' file has been generated by scripts/score_generator.py.
"""

import logging
import time
from pathlib import Path
from antescofo import AntescofoClient, Event, EventType

# --- Configuration ---
# Antescofo listens for commands on port 5678 (Python sends here)
ANTESCOFO_SEND_PORT = 5678
# Python listens for events on port 9999 (Antescofo sends here)
PYTHON_RECEIVE_PORT = 9999
SCORE_FILE = Path("simple_demo_score.asco.txt")

# Set up logging for visibility
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def on_action_trace(event: Event):
    """Handler for action execution messages coming from Antescofo."""
    if isinstance(event.data, tuple) and len(event.data) > 5:
        # Action trace format: (name, type, father, now, rnow, message)
        print(f"[{event.data[1].upper()}] {event.data[5]}")
    else:
        print(f"[TRACE] {event.data}")


def on_tempo_change(event: Event):
    """Handler for tempo changes coming from Antescofo."""
    print(f"[INFO] Antescofo Tempo changed to: {event.data} BPM")


def main_demo():
    """Runs the full Antescofo interaction demonstration."""
    print("=" * 60)
    print("      Starting Antescofo/PureData OSC Demo")
    print("=" * 60)
    print(f"1. Python Client (Sends commands to {ANTESCOFO_SEND_PORT})")
    print(f"2. Python Client (Receives events on {PYTHON_RECEIVE_PORT})")
    print("-" * 60)

    # Ensure the score file exists
    if not SCORE_FILE.exists():
        print(f"\n[ERROR] Score file not found at {SCORE_FILE.resolve()}")
        print("Please run scripts/score_generator.py first.")
        return

    client = AntescofoClient(
        host="localhost",
        port=ANTESCOFO_SEND_PORT,
        receive_port=PYTHON_RECEIVE_PORT,
    )

    try:
        # 1. Connect
        client.connect()

        # 2. Subscribe to events
        client.on(EventType.ACTION_TRACE, on_action_trace)
        client.on(EventType.TEMPO, on_tempo_change)

        # 3. Load the score into Antescofo
        print(f"\n[CMD] Loading score: {SCORE_FILE.name}")
        # Note: Antescofo needs the absolute path to load the score correctly
        client.load_score(SCORE_FILE.resolve())

        # 4. Start playback
        print("[CMD] Starting playback...")
        client.start()

        # 5. Dynamic control (sent from Python to Antescofo)
        client.wait(3)
        print("[CMD] Setting tempo to 150 BPM...")
        client.set_tempo(150.0)

        # 6. Wait for score to finish
        print("[INFO] Waiting 5 seconds for score actions to trigger...")
        client.wait(5)

        # 7. Stop
        print("[CMD] Stopping playback.")
        client.stop()

    except Exception as e:
        print(f"\n[FATAL ERROR] An Antescofo communication error occurred: {e}")
        print("\n*TROUBLESHOOTING TIP: Ensure Pd patch is loaded and OSC ports are set correctly.*")

    finally:
        client.disconnect()
        print("\n[INFO] Demo Finished. Client disconnected.")


if __name__ == "__main__":
    main_demo()
